apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: "androidx.navigation.safeargs.kotlin"

// AboutLibraries plugin
apply plugin: 'com.mikepenz.aboutlibraries.plugin'

// for appending to version name
static def buildDate() {
    return new Date().format("yyyyMMdd")
}

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"
    defaultConfig {
        applicationId "cy.org.rise.obsai"
        minSdkVersion 21
        targetSdkVersion 29

        // versioning
        versionCode 1
        def versionMajor = 0
        def versionMinor = 6
        def versionPatch = 0
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Enable incremental annotation processing for Room
        // see https://stackoverflow.com/a/58122855/3755276
        javaCompileOptions {
            annotationProcessorOptions {
                arguments = ["room.incremental": "true"]
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8.toString()
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // Kotlin coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.4'

    // Recycler view
    implementation "androidx.recyclerview:recyclerview:1.1.0"

    // Settings/Preference library
    implementation "androidx.preference:preference:1.1.0"

    // Assent runtime permissions library https://github.com/afollestad/assent
    implementation 'com.afollestad.assent:core:3.0.0-RC4'
    implementation 'com.afollestad.assent:rationales:3.0.0-RC4'
    // Material dialogs library (same author) https://github.com/afollestad/material-dialogs
    implementation 'com.afollestad.material-dialogs:input:3.3.0'

    // Lifecycle libraries
    def lifecycle_version = "2.2.0"
    def arch_version = "2.1.0"

    // ViewModel library
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:$lifecycle_version"
    // LiveData
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_version"

    // Saved state module for ViewModel
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:$lifecycle_version"

    // Annotation processor (alternately - if using Java8, use the following instead of
    // lifecycle-compiler)
    //    kapt "androidx.lifecycle:lifecycle-compiler:$lifecycle_version"
    implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"

    // optional - ReactiveStreams support for LiveData
    implementation "androidx.lifecycle:lifecycle-reactivestreams-ktx:$lifecycle_version"

    // optional - Test helpers for LiveData
    testImplementation "androidx.arch.core:core-testing:$arch_version"


    // Room persistence library (SQLite ORM)
    def room_version = "2.2.4"
    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"

    // Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"

    // RxJava support for Room
    implementation "androidx.room:room-rxjava2:$room_version"

    // Guava support for Room, including Optional and ListenableFuture
    // implementation "androidx.room:room-guava:$room_version"

    // Test helpers
    testImplementation "androidx.room:room-testing:$room_version"


    // Navigation component library - https://developer.android.com/guide/navigation
    def nav_version = "2.3.0-alpha03"

    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"

    // Dynamic Feature Module Support
    implementation "androidx.navigation:navigation-dynamic-features-fragment:$nav_version"

    // Testing Navigation
    androidTestImplementation "androidx.navigation:navigation-testing:$nav_version"


    // Picasso - Image loader - https://github.com/square/picasso
    implementation 'com.squareup.picasso:picasso:2.71828'

    // CameraView library - https://github.com/natario1/CameraView
    api 'com.otaliastudios:cameraview:2.6.1'

    // Android Image Cropper - https://github.com/ArthurHub/Android-Image-Cropper
    api 'com.theartofdev.edmodo:android-image-cropper:2.8.0'

    // Play Services location provider
    implementation 'com.google.android.gms:play-services-location:17.0.0'

    // Maps library, uses OpenStreetMap - http://osmdroid.github.io/osmdroid/
    // removed, leaving this in case it's needed in the future
    // implementation 'org.osmdroid:osmdroid-android:6.1.0'

    // Google Maps library
    implementation 'com.google.android.gms:play-services-maps:17.0.0'

    // Preference manager
    implementation "androidx.preference:preference-ktx:1.1.0"

    // Drawerlayout
    implementation "androidx.drawerlayout:drawerlayout:1.0.0"

    // AboutLibraries library
    implementation "com.mikepenz:aboutlibraries-core:8.0.0-rc01"
    implementation "com.mikepenz:aboutlibraries:8.0.0-rc01"

    // ACRA crash reporting library https://github.com/ACRA/acra
    def acraVersion = '5.1.3'
    implementation "ch.acra:acra-mail:$acraVersion"
    implementation "ch.acra:acra-dialog:$acraVersion"
    implementation "ch.acra:acra-limiter:$acraVersion"

    // Retrofit https://github.com/square/retrofit
    implementation "com.squareup.retrofit2:retrofit:2.7.2"

    // Changelog https://github.com/MFlisar/changelog
    implementation 'com.github.MFlisar:changelog:1.1.6'
}
